name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requierements.txt

      - name: Lint Code
        run: |
          source venv/bin/activate
          pylint model_pipeline.py main.py || true  # Ignore failure to prevent breaking CI

      - name: Run Tests
        run: |
          source venv/bin/activate
          pytest tests/ --verbose

      - name: Build & Train Model
        run: |
          source venv/bin/activate
          python main.py
